### ISSUE TITLE
Adding the format "phone number" for  all the countries

### ISSUE THREAD

**Issue by ismnoiet** [mohsen1/json-to-json-schema#4]
For example we have as a js object 
`{phone:'+21321405060}`
and after calling **convert()** we get 
`{type: 'string', format: 'phone',country: 'algeria(dz)'}`
@mohsen1  what you think  about it ?

**Comment by mohsen1** [comment]
I'm not sure if country is part of the spec. Where did you see it?

**Comment by ismnoiet** [comment]
@mohsen1 It is just an idea, i forget that we have to respect the spec,
you know sometimes even with simple things we try to invent and make it complicated

**Comment by mohsen1** [comment]
You can work on date and date-time formats.

**Comment by ismnoiet** [comment]
Yes i can, 
i'm currently working on it :)
